package enums;

public enum Actions {
	START, SAIL, BUY, SELL, VIEW_SELL, CONTINUE, LOG_NEXT, VIEW, LOG_PREV, NEXT_INV, PREV_INV, NEXT_SELL, PREV_SELL, REPAIR, PAY, CONFIRM_MENU, GO_TO_ISLAND, OPEN_STORE, CHOOSE_ROUTE, OPEN_INVENTORY, OPEN_DECK, MAIN_MENU, OPEN_BUY, OPEN_SELL, CLOSE_BUY_SELL, SHOW_REWARD, DUMP, CONFIRM_DUMP, TALK, END, GET_ITEM, VIEW_REWARD, OPEN_DUMP, CLOSE_STORE, FIGHT, FLEE, VIEW_SHIP, SURRENDER, CONFIRM_SURRENDER, PIRATE_MENU, NONE
}
