package enums;

public enum Actions {
	START, SAIL, BUY, SELL, LOG_NEXT, LOG_PREV, NEXT_INV, PREV_INV, OPEN_STORE, CHOOSE_ROUTE, OPEN_INVENTORY, OPEN_DECK, MAIN_MENU, OPEN_BUY, OPEN_SELL, CLOSE_BUY_SELL, TALK, CLOSE_STORE, NONE
}
